Collisions
ucsd-cse125-sp22/cse125-sp22-group1 pull request #15
Opened 2022-04-10 06:50 UTC by alistairgray42

Add support for collisions to the physics engine.

i will add more to this pr description when my laptop is not on the verge of death

2022-04-10 15:32 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +    for p1_corner in p1_corners {
There's a pathological case which is likely not a practical problem but which passes this collision test: two cubes centered at the same location, one of which is rotated, say, 45 degrees relative to the other. This can be remedied by checking more points (the center of the object, center of the hitbox's edges) but I don't think that's necessary at the moment

2022-04-11 01:39 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +    pub fn collide_players(&self, other: &PlayerEntity, time_step: f64) -> Option<PlayerEntity> {
Is `Option` a semantically good thing to use here? I often see it for, like, error handling, but this other usage made sense to me

2022-04-11 19:25 UTC, alistairgray42 commented on chariot-server/src/game.rs
> +    game_state: ServerGameState,
This is very much a single idea (that may be far from best) for how to structure server-side state; suggestions welcome

2022-04-11 23:43 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +    game_state: ServerGameState,
It'll work for now, no foreseeable issues.

2022-04-12 00:19 UTC, KNOXDEV requested changes
@alistairgray42 sending back to you. Great work on what you have, I'm giving some suggestions on the comments you left as well as some things I noticed. Let me know what you think.

2022-04-12 00:19 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +    for p1_corner in p1_corners {
I think we can solve this issue and simplify your existing algorithm by using the industry standard Axis-Aligned Bounding Box technique instead. Basically, instead of rotating the bounding boxes, don't. It actually doesn't really matter that much in practice. 

https://developer.mozilla.org/en-US/docs/Games/Techniques/3D_collision_detection

2022-04-12 00:19 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +    pub fn collide_players(&self, other: &PlayerEntity, time_step: f64) -> Option<PlayerEntity> {
`Option` should be used when a function will occasionally, in *normal* execution, need to indicate there is no return value.

Conversely, `Result` is used when the algorithm could have an *exceptional* error that the caller will need to handle.

I think that it is appropriate in this case to use `Option`.

To connect these concepts to another language like Java, `Option` is Rust's `null` and `Result` is Rust's checked exceptions.

2022-04-12 00:19 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +        // x-diwection Owo a-and we 😳 👉 👈 t-touched edges 🥺
this comment was corrupted somehow, please remove for common decency reasons

2022-04-12 00:19 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +        for (index, player) in self.game_state.players.iter().enumerate() {
I see that you're doing a lot of cloning and copying when I think you could do all of this more efficiently with references.

For example, `self.game_state.players.iter_mut()` will allow you to iterate over mutable references to players and most likely do the same things.

From there, you could `filter` out the current player and recollect them into another vector for passing into `do_physics_step` without doing any additional cloning.

It's a little bit complicated but I would advise doing it. If you need any pointers just lmk

2022-04-12 00:19 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +    pub fn do_physics_step(
It's not top priority, but if you wanted to generalize this function to get passed in an arbitrary vector of bounding boxes that aren't necessarily players, that would be useful for future PRs where you'll need to handle player's colliding with terrain.

2022-04-12 00:53 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +        let theta;
so true

2022-04-12 00:53 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +        let center = DVec3::new(
so true

2022-04-12 00:55 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +        // x-diwection Owo a-and we 😳 👉 👈 t-touched edges 🥺
![image](https://user-images.githubusercontent.com/28539155/162856944-8bc5f1df-51a6-45ca-9b9f-ca1a303fb0a1.png)
i'll have you know i paid good money for this comment

2022-04-13 06:01 UTC, alistairgray42 commented on chariot-server/src/physics/mod.rs
> +    pub fn do_physics_step(
Yeah, I'd prefer to confine this PR to player-player collisions only at the moment

2022-04-13 06:10 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +        // corners of the bounding box (source: trust me bro)
i can draw a diagram for this if anyone needs convincing

2022-04-13 06:50 UTC, KNOXDEV requested changes
Hey Alistair, loving the changes you made. Thanks a bunch, the AABB are for sure a much better way to go.

I'm still confused by several things because I'm not used to everybody's coding styles yet. I was hoping you could help me understand a few remaining places where the structure didn't click for me.

Thanks in advance Alistair!

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/player_entity.rs
> +    pub x_size: f64,
is there a reason you didn't make this a DVec3 like the others? Idk if it would be better but I feel like it would be more consistent at least.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/player_entity.rs
> +#[derive(Copy, Clone, PartialEq)]
I'm wondering why you've added Copy, Clone, and PartialEq to every struct in the physics engine. 

I tend to leave these underived since generally, Copying, Cloning and field-by-field Equality are operations that can be avoided in most cases without too much additional effort and some usage of references and borrowing. Moreover, if they can be avoided, they should be.

Additionally, by leaving them underived, the compiler will throw an error when you forget to pass by reference, which is a net good thing.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +                .filter(|&other_player| other_player != player)
I'm not sure if this equality check is a good way to go about this. Deriving PartialEq on the PlayerEntity struct means that the definition of equality is that every field in the struct is compared for equality to see if the overall structs are equal. I think you can see why this might be undesirable.

You can just add enumerate before the filter to filter by index, similar to how you did before. I think that would be a good way to go about this.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +    fn get_bounding_box_corners(&self) -> [[f64; 2]; 3] {
Is the name of this function still representative? It looks like this returns dimensions and not corners.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +        return [[min_x, max_x], [min_y, max_y], [min_z, max_z]];
This function returns min and max of all three dimensions. Is there any case where min_x would not simply be the same distance from the center as max_x but in the other direction?

I only ask because you compute min_x and max_x separately.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +    let bounding_box_1 = p1.get_bounding_box_corners();
So, I notice with this algorithm that over the course of a single physics loop, you compute the bounding box of each player `n` times (where `n` is the number of players). That makes each physics loop `n^2` in terms of the most computationally expensive part of the calculation.

It also has the side effect of making physics non-deterministic. That is to say, the order in which physics interactions are computed is dependent on their natural ordering of players in the PlayerEntity vector.

If instead you compute the AABB of every player once at the start of the physics loop and use those for every computation, you bring the algorithm back down to linear while also making physics independent of the uncontrollable player order.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/collisions.rs
> +    return check_bounding_box_collisions(&p1, &p2) || check_bounding_box_collisions(&p2, &p1);
Does this really need to be computed twice here? I feel like this operation should be commutative.

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +                post_physics_PlayerEntity = result;
I think Rust doesn't really play nicely with the pattern you're using here of "replacing" the entity position with a new one. I think you should have collision calculation functions be mutable functions on PlayerEntity so they can just modify the internal velocity data.

This is a bit of a more subjective piece of advice but in my experience it can be a lot cleaner. Do you have a strong reason for doing it this way?

2022-04-13 06:50 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +                post_physics_PlayerEntity = result;
This goes for most of the physics engine by the way, I notice you take a functional approach of having pure functions with inputs and outputs while avoiding state.

This is a good approach in a lot of languages but I think mutable functions are a lot more clear in Rust specifically.

2022-04-13 18:32 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +    return check_bounding_box_collisions(&p1, &p2) || check_bounding_box_collisions(&p2, &p1);
True! The previous version wasn't commutative, good catch.

2022-04-13 18:41 UTC, alistairgray42 commented on chariot-server/src/physics/collisions.rs
> +        return [[min_x, max_x], [min_y, max_y], [min_z, max_z]];
Yes, this is true

2022-04-14 19:13 UTC, alistairgray42 commented on chariot-server/src/physics/player_entity.rs
> +    pub x_size: f64,
Sure

2022-04-15 05:16 UTC, alistairgray42 commented on chariot-server/src/physics/mod.rs
> +                post_physics_PlayerEntity = result;
I understand the point here, and I definitely tend too much towards functionalbrain. I've replaced this specific instance you're committing on in the most recent commits, but am elsewhere still doing roughly functional things. In particular, I think this is justified in `simulate_game`: when colliding with multiple other objects simultaneously, each collision is going to cause a change to the velocity, but we want to use the original properties of all objects to calculate the new velocities, so we can't change velocity in-place without copying at some point.

2022-04-15 05:20 UTC, alistairgray42 commented on chariot-core/src/entity_location.rs
> +#[derive(Copy, Clone)]
Would like to not have to derive Copy and Clone for these, but I think it's necessary(?) if `do_physics_step` doesn't mutate state, which I think it shouldn't do.

2022-04-15 17:42 UTC, KNOXDEV commented on chariot-core/src/entity_location.rs
> +#[derive(Copy, Clone)]
If `do_physics_step` just returns a new location, it shouldn't need to copy anything, unless I'm misunderstanding.

2022-04-15 18:06 UTC, KNOXDEV requested changes
Looking very good at this point. Just a couple last comments and you can take a look and let me know what you think. 

Overall, I think eventually we'll be looking at a refactor that decouples the physics engine from the concept of Players and has FreeBodyEntity be its own structure with most of the logic, but I think this will not be too difficult and can be safely deferred.

2022-04-15 18:06 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +        let dims = props.get_bounding_box_dimensions();
Based on how frequently this call gets made, I think you should store the bounding box inside of the PlayerEntity itself. That way you can reuse it in various functions without needing to either recompute it every time or pass it in as arguments constantly.

At the beginning of the loop, you just call `player.update_bounding_box` to bring the bounding boxes up to date with the position and rotation, then you can use them in the physics computation as `self.bounding_box`, etc.

For the record, this is a pretty common approach.

How does that sound?

2022-04-15 18:34 UTC, alistairgray42 commented on chariot-server/src/physics/mod.rs
> +        let dims = props.get_bounding_box_dimensions();
Yeah, I went back and forth on that (didn't want to have state get out of sync but tbh that's probably not much of a real concern). Probably is cleaner like this, yes

2022-04-15 18:39 UTC, KNOXDEV approved these changes
:)

2022-04-15 18:40 UTC, merged