Adding WebSocket Connection for Client
ucsd-cse125-sp22/cse125-sp22-group1 pull request #18
Opened 2022-04-15 07:59 UTC by trulyronak

Basing it off of comments from @KNOXDEV and primarily this repo: https://github.com/snapview/tungstenite-rs

*heavily WIP*

Current plan:

- setup a simultaneous web socket connection while we start the main game loop in the networking
- create some sort of shared packets / shared input/output stream that the web sockets and the tcp game loop can share / use to communicate with each other
- send messages back and forth with each other

2022-04-15 17:25 UTC, KNOXDEV commented
I know that this is still a heavy work in progress, but I just wanted to say that this is a lot cleaner and less heavy and easier to understand. Thanks for your hard work, Ronak!

One thing I would add at this stage is that websocket messages are currently handled in separate threads. I wonder if that's necessary, since it complicates the logic with Mutexes, etc. The current TCPStream implementation manages to handle a single threaded approach, so that might be a good example to look at if a single-threaded approach is possible.

2022-04-18 22:42 UTC, trulyronak commented
ready for review now

- mirrors much of the existing tcp networking code, so i think there's probably some code reuse I could have done (i based my models off of aarons, but found i didn't need as much stuff).
- right now, the server just echos back any web socket messages for testing purposes

to test
```
cd chariot-server/
cargo run

# in another shell
cd chariot-client/
cargo run

# in another shell
cd chariot-web/
yarn install
yarn dev
```

Why Next?
- gonna deploy it with vercel, no issues with deployment
- planning on just hard coding / maybe configuring a way to connect to a specific server
- this way we can do more fun things with the web ui (easier pwa / i just like having dynamic open graph tags)

2022-04-18 23:01 UTC, alistairgray42 commented on chariot-core/src/networking/ws.rs
> +    fn test_connection() {}
Either have an actual test here (idk to what extent you can copy the TCP connection one but if not much modification is needed that might work) or remove this

2022-04-19 06:02 UTC, alistairgray42 commented on chariot-server/src/game.rs
> +                Ok(stream) => {
`if let` (https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html) is the more idiomatic way to do both the `Some` and the `Ok` matchings here (for when you don't want to do anything in the other `None` or `Err` cases)

2022-04-19 15:20 UTC, KNOXDEV requested changes
very good, just a few minor nit picks, but no major changes at this point.

Great work, Ronak!

2022-04-19 15:20 UTC, KNOXDEV commented on chariot-server/Cargo.toml
> +tungstenite = "0.16.0"
Fun trick: you can reexport tungstenite as a module from chariot-core. This is considered the idiomatic way to do it, rather then using the dependency twice.

https://github.com/rust-lang/api-guidelines/discussions/176

2022-04-19 15:20 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +                        self.ws_connections.iter_mut().for_each(|ws| {
Add a comment here indicating this should be removed at some point so we don't forget haha.

2022-04-19 15:20 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +                Ok(stream) => {
I would actually say do a while let, loop on incoming until you've depleted it.

2022-04-19 15:20 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +        if message_to_send.len() > 0 {
I would create a send_ws_broadcast function instead so you can just call it from each specific match case.

2022-04-21 00:20 UTC, KNOXDEV approved these changes
Great work Ronak!

2022-04-21 00:26 UTC, merged