Crazy button stuff
ucsd-cse125-sp22/cse125-sp22-group1 pull request #19
Opened 2022-04-17 22:28 UTC by TheCrossBoy

Rust go brrrr so there's two ways you can deal w input atm:

1. Implement the trait `Watching`, with various input functions, then have the GameClient call whatever object needs to handle input. This is probably most useful for things like menu UIs, where there might be lots of buttons or things where it's easier to handle each instance on itself
2. Use GameClient.pressed_buttons, which is a set containing all pressed buttons

I'll do some work to clean it all up and make it less messy (and uncomment the stuff I commented so I could test without a server)

2022-04-19 17:29 UTC, nickwn approved these changes
LGTM, Just merge main

2022-04-19 17:29 UTC, nickwn commented on chariot-client/src/game.rs
> +    pressed_keys: HashSet<VirtualKeyCode>,
Can we store this on the Application? Otherwise NBD

2022-04-24 19:11 UTC, KNOXDEV requested changes
Just minor points this time Josh. Not everything necessarily needs responding to. Great work overall!

2022-04-24 19:11 UTC, KNOXDEV commented on chariot-server/src/game.rs
> +                                // self.players[figureOutWhoThisIs()].player_inputs.engine_status = EngineStatus::Neutral;
this will just be `self.game_state.players.get(i)` I think.

2022-04-24 19:11 UTC, KNOXDEV commented on chariot-client/src/main.rs
> +    event_loop.run(move |event, _, control_flow| {
This `event_loop` block is kind of sprawling and difficult to read, but I don't have any advice on how to fix it atm. Just noting.

2022-04-24 19:11 UTC, KNOXDEV commented on chariot-client/src/game.rs
> +    pub fn send_input_event(&mut self, event: InputEvent, enable: bool) {
Idk about this boolean `enable`. Is this just indicating whether the input has started or stopped? I feel like that's still just an input event, but with `EngineStatus.Neutral`, etc.

2022-04-24 23:40 UTC, TheCrossBoy commented on chariot-client/src/main.rs
> +    event_loop.run(move |event, _, control_flow| {
I attempted a bit of something to try to fix this, not fully solved but it's at least a bit less cluttered I think

2022-04-24 23:53 UTC, TheCrossBoy commented on chariot-client/src/game.rs
> +    pub fn send_input_event(&mut self, event: InputEvent, enable: bool) {
I originally had something typed out to explain my reasoning, but I think you're actually right that this would make more sense to figure out on the client.

I'll do some shifting of logic and such to have this determination be here instead.

2022-04-25 01:17 UTC, TheCrossBoy commented on chariot-client/src/game.rs
> +    pub fn send_input_event(&mut self, event: InputEvent, enable: bool) {
Alrighty, this has been moved to the client with the following solution:

- `Application.get_input_event` will turn a key into an input
- `Application.invert_event` will attempt to turn a given input event into its "inverse" (accel/brake -> neutral, etc), when relevant
- If an input's event has an inverse, then it will send that signal to the server. This has the added benefit of not affecting anything when we do "single click" buttons like abilities/powerups/etc, because it just won't have an inverse and thus just won't send any packets to the server when lifted.

2022-04-25 01:19 UTC, KNOXDEV approved these changes
Looks great! The extra comments are a nice touch. Thanks Josh!

2022-04-25 01:25 UTC, merged