Add in server logic for loading the map/assets
ucsd-cse125-sp22/cse125-sp22-group1 pull request #37
Opened 2022-05-10 00:58 UTC by TheCrossBoy

Very WIP still and been messing with git for too long now

2022-05-15 11:06 UTC, TheCrossBoy commented
Alright cool stuff done now! With some extra bonus stuff for free! This PR:

- Loads maps on the server and the client
- Imports trigger data into the server
- In blender, set the "Object Data Properties" for the following:
  - `render` (0, 1 default): Whether or not to render the object
  - `purpose` (string): Tell the server this object has a purpose, and should be loaded (currently supports `trigger` and has placeholders for `collider`)
  - `trigger` (string): Tell the server which trigger type this object is
  - `zone_id` (int): The ID of the zone trigger
- Using the "mario kart wii" style tracking, has lap logic & tracking (see below)
- Client/server communication for lap updates/placement updates
- Clarifying names of checkpoints
  - `MajorCheckpoint` -> `Zone`: "What section of the map am I in?"
  - `MinorCheckpoint` -> `Checkpoint`: "Where should I respawn if I were to fall off the map?"

![image](https://user-images.githubusercontent.com/15060061/168469140-f49b9302-5cbb-48ed-a52f-4a1e5c3d7fe4.png)

**Note**: The map file currently uploaded to google drive has the rendering of the triggers still enabled on the client to make it easier for us to test/see what's happening. This is changed exclusively through blender, so it doesn't affect this PR.

Please let me know what you think!

What I *need* to do still:
- Write tests :,^)
- Import `Checkpoint`s
- Write backend for Powerups
  - This should take like 5 mins, but the "loading" part is something that I'd like to get a better system up for (having the server place them in "powerup placeholders", so we don't have to place them individually

What I would *like* to do (probably on other PRs):
- De-anonymize *all* the random primitives we have with `type`s. Reading `(u8, (u8, u8, u8, f64))` can get confusing, whereas `(PlayerID, (LapNumber, ZoneID, CheckpointID, f64))` is more clear.
- I'd like to have the client connect to the server _before_ loading the map. Then, the server tells the client which map file to load, and the client will tell the server when it has fully loaded in so the server doesn't start the game too early. This has the advantage of making adding extra maps incredibly easy. 

wow this was a big comment lol

2022-05-15 17:10 UTC, alistairgray42 commented on chariot-server/src/game/map.rs
> +    // good god figuring out type stuff here made me want to pivot to javascript permanently
:crab:

2022-05-15 17:22 UTC, alistairgray42 submitted a review, later dismissed
Beautiful! 

Something to be aware of from an end-user POV is that it'd be super frustrating to accidentally miss a zone - we should make sure that they're large enough (and walls are strategically placed) such that it's impossible to miss all the zones if you're zooming around the track.

2022-05-15 18:03 UTC, trulyronak commented on chariot-server/src/game/map.rs
> +    // good god figuring out type stuff here made me want to pivot to javascript permanently
typescript ftw

2022-05-16 01:03 UTC, alistairgray42 requested changes
Mostly looks pretty good to me! I notice that `player.current_powerup` never actually gets populated - is the plan to handle this in a different PR?

2022-05-16 01:42 UTC, TheCrossBoy commented on chariot-server/src/game/powerup/pickups.rs
> +            // Give a powerup
I was under the impression that we were only having the boxes, so I think I'll actually rename `PowerupTrigger` to `ItemBox` to make it more clear. The intention is that `give_powerup` will pick a random `PowerUp`, and give it to the player.

2022-05-16 01:43 UTC, TheCrossBoy commented on chariot-server/src/game/powerup/action.rs
> +            _ => todo!(),
Yeah definitely shouldn't be - was mostly just going to let that be a separate PR so that this can be merged in.

2022-05-16 02:24 UTC, alistairgray42 approved these changes

2022-05-16 02:38 UTC, merged