State management
ucsd-cse125-sp22/cse125-sp22-group1 pull request #38
Opened 2022-05-10 09:46 UTC by alistairgray42

- Makes server-side state more explicit by introducing a `GamePhase` enum, which denotes when certain kinds of packets are expected/allowed/handleable
- Moves code out of `server/game.rs`, to better break things up
- (to do) Use packets of a new type to notify the clients as to what state the server is in, because explicit is good
- (to do) Add phase transitions
- (to do) Add some kind of bypass to ignore all this and let client folks not have to worry about rounding up three friends to play with when developing

would like comments on:
- the names of the phases, naming things is hard
- what exactly this bypass looks like (I'm thinking a config file option?)

2022-05-10 23:21 UTC, trulyronak commented on chariot-server/src/game/mod.rs
> +            self.check_audience_voting();
this should go inside `simulate_game`

2022-05-10 23:21 UTC, trulyronak commented on chariot-server/src/game/phase.rs
> + *  Phase 5 is marked by the server's AllDone packet.
I think we should have phase 'PlayingWhileVoting` and `PlayingWithDecision`, where the first stage is while players play with no effect and the second stage is players playing with the effect added. These two phases don't make enough sense to be separated to me + i feel are a bit confusing. 

```suggestion
 * 3. GamePhase::PlayingWhileVoting
 *     Players will be driving around normally and the clients will simply 
 *     display "The Audience is Deciding Your Fate" (for juice). 
 *     State: `timeUntilVotingTally`, `questionPrompt`
 *
 * 4. GamePhase::PlayingWithDecision
 *     Players will be doing their thing WITH some new effect in place. 
  *    This effect only exists during this phase. 
 *     State: `timeUntilDecisionEnds`, `winningEffect` (this would be 
  *    an enum or something so we can 
 *     (a) display it on clients and (b) do special server logic)
 *     The transition from Phase 4 to Phase 5 is marked by the server's
 *     AllDone packet (sent when someone wins the game)
```

2022-05-10 23:21 UTC, trulyronak commented on chariot-server/src/game/mod.rs
> +            GamePhase::PlayingBeforeVoting | GamePhase::PlayingWithVoting => {
would be nice to have some code that runs for both stages + some code that only runs for one stage (so it can do mutual code + phase specific code)

2022-05-10 23:39 UTC, TheCrossBoy requested changes
Cool stuff, very nice organizational changes too will make it easier to find stuff going forward!

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/src/game/mod.rs
> +    waiting_for_player_ready_state: WaitingForPlayerReadyState,
Is there a reason why these are all being stored separately, rather than having them be part of the GamePhase enum? i.e. something like:
```rust
enum GamePhase {
    WaitingForPlayerReady(WaitingForPlayerReadyState),
    // etc
}
```

I don't think we'd need to keep the CountingDownToGameStartState stored around within the server's state when we are, say, in the PlayingBeforeVotingState, right?

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-client/src/graphics.rs
>          let chair_import = chair_import_result.expect("Failed to import chair");
nit: this would probably be neater as a one-liner (resources.import().expect()) since we don't care about the result otherwise 
edit: along with the other place in our codebase as a whole we do that

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/config.yaml
> +bypass_multiplayer_requirement: true
what's this file for in comparison to the settings.rs file's stuff? is this used somewhere atm?

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/src/game/mod.rs
> +pub struct Map {
mildly annoyed that i've moved this to a seperate file 3 times but because git is funny it somehow never actually happened in the mess of a history i was dealing with but alas

so i now return this suggestion to you: probably smart to move this to its own file within the game module, since it'll get expanded upon

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/src/game/phase.rs
> +pub enum GamePhase {
See earlier comment about storing states within these

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/src/game/voting.rs
> +        poll_time: Duration,
is it possible to have this be an arbitrary number of options (in a vec) instead of 4? i.e. question: String, options: Vec<String>, poll_time: Duration?

I think it should be possible to send that to the websocket as well by explicitly stating the number of options, then reading that many, right?

2022-05-10 23:39 UTC, TheCrossBoy commented on chariot-server/src/game/voting.rs
> +        poll_time: Duration,
This is probably not something added in this PR but this is when I'm seeing it most recently, so

2022-05-10 23:43 UTC, trulyronak commented on chariot-server/src/game/voting.rs
> +        poll_time: Duration,
I'm going with 4 hard coded options just because I don't want the UI to render more than 4 options → we could do an array of fixed size 4 (which is what it is on typescript actually) but idk how force array size with rust types

2022-05-11 00:20 UTC, KNOXDEV commented on chariot-server/src/game/voting.rs
> +        poll_time: Duration,
`options: [String; 4]`

2022-05-11 00:21 UTC, KNOXDEV commented on chariot-server/src/game/mod.rs
> +    waiting_for_player_ready_state: WaitingForPlayerReadyState,
:+1: to this suggestion

2022-05-11 00:43 UTC, trulyronak commented
closing because i've taken over this PR and I don't want to be able to approve my own PR

2022-05-11 00:43 UTC, closed without merging