Peter/audio
ucsd-cse125-sp22/cse125-sp22-group1 pull request #39
Opened 2022-05-10 17:56 UTC by potor10

# Audio Engine
This is the audio engine for chariots, programmed in Rust using Rodio.

## Audio Context
Define & Set up the audio output devices used to playback audio

Usage: `AudioCtx::new();`

### Struct
* _stream: `OutputStream`
* stream_handle: `OutputStreamHandle`

## Source Options
Options that modulate the source of audio that is being played

Usage: `SourceOptions::new();`

### Struct
* fade_in: `Duration`,
* repeat: `bool`,
* skip_duration: `Duration`,
* take_duration: `Duration`,
* pitch: `f32`,

## Audio Thread
A multipurpose class that is designed to wrap the main Audio Sink (thread that plays audio in Rodio) and provide additional control over playback.

Usage: `AudioThread::new(&AudioCtx, PathBuf, SourceOptions);`

### Struct
* time_start: `SystemTime`,
* volume: `f32`,
* pitch: `f32`,
* file: `File`,
* sink: `Sink`,
* src_opt: `SourceOptions`

## Audio Source
A class designed to maintain and control all Audio Threads.

Usage: `AudioSource::new(Path);`

### Struct
* tracks: `Vec<PathBuf>`,
* threads: `Vec<AudioThread>`,
* volume: `f32`,
* pitch: `f32`,
* emitter_pos: `[f32; 3]`,
* left_ear: `[f32; 3]`,
* right_ear: `[f32; 3]`,

## Instructions
1. Begin with the relevant imports

```
use audio::{AudioCtx, SourceOptions, AudioSource};
mod audio;
```

2. Set up an audio context (this is what determines what output we are using on the device)
By default, it is automatically configured to identify the standard output the device is using.

`let audio_ctx = AudioCtx::new();`

3. Create an AudioSource. This manager is a collection of audio threads that is able to be controlled as a group. It's a good idea to separate music, ambient, and SFX tracks via their own audio managers.

```
let mut music_manager = AudioSource::new("audio/music");
let mut amb_manager = AudioSource::new("audio/ambient");
let mut sfx_manager = AudioSource::new("audio/sfx");
```

4. Define a sound source options and play sounds

Normal playback, will play alongside all other current sounds. Good for SFX.
`track_id` is the usize index of the track to play in the source directory.

```
let src_opt = SourceOptions::new();
sfx_manager.play(track_id, &audio_ctx, src_opt);
```

Crossfade playback, will play a new sound fading in with all other current sounds fading out. Good for Music & Ambient where only 1 thing should be playing at a time.

```
// 1000 ms fade in & fade out
let src_opt = SourceOptions::new();
music_manager.play_cf(track_id, &audio_ctx, src_opt, Duration::from_millis(1000));
```

Use additional control settings if necessary:

```
// Volume control
music_manager.set_volume(1.0);
```

```
// Pitch control (affects playback speed)
music_manager.set_pitch(1.0);
```

2022-05-10 20:50 UTC, KNOXDEV commented
Let me start by giving some high level feedback.

First, great work Peter! This is incredible stuff. The documentation is especially appreciated. 

Can you create a subfolder for the audio submodule and break up the `audio.rs` file into a file for each major struct? Its a bit easier to maintain then one giant 300+ line rust file. You can glue it all together with `audio/mod.rs`. You can also put the audio `README` into that folder, I think that would be a good place for it. https://doc.rust-lang.org/rust-by-example/mod/split.html

To address the points you've brought up in the PR:

### Generic Sink implementation in AudioThread

I think the "rusty" way to handle this is to have a AudioSink sync enum that can have either Sink or SpatialSink. When you go to use this, you'll use a match statement to disambiguate.

### Manipulating singular audio threads

Since AudioSource can't give up ownership to the AudioThreads it owns, really the easiest, if most verbose solution is to simply provide functions on AudioSource that allow you to tweak parameters for a particular thread. It's up to you if this is more preferred to what you have right now.

One other thing I'll note is that it's not a huge issue either way. Its possible we won't run into the use case at all, or if we do, rather than allow control over the AudioThread, we'll expose the exact functionality we need in that moment on AudioSource and we'll be good to go.

### Poor performance

If we run into the issue "in production" we can address it then. Not sure if we'll need more than 2-3.

### Reading from path buffer rather than loading a source from memory

I think the solution here will be to (lazily) load the file into memory and just borrow immutable references to it whenever we create a new source. The wrapping source around the buffer will copy the individual bytes as the file is played.

## some last points

Overall, I notice there's a lot of `unwrap()` since a lot of the device interaction calls could fail at any time. It would be great if instead of `unwrap()` (which crashes the program if, say, I unplug my headphones) we just kill that audio thread or don't play the sound in that moment.

In the (hopefully few) cases where we need to unwrap, it would be great if we used `expect()` and left a message that informed us of the context. 

Thats all for now Peter, and thanks again for all the work!

2022-05-10 20:50 UTC, KNOXDEV requested changes
see above

2022-05-10 21:15 UTC, alistairgray42 commented on chariot-client/src/audio.rs
> +  pub fn set_fade_in(&mut self, duration: Duration) {
In general, getters and setters will tend to be less rusty than making the fields of the struct public (for non-computed properties at least) - it also shouldn't really be the case that these methods are getting called by enough other code (because of the layers on top) for this to be worth it, imo

2022-05-16 23:00 UTC, potor10 commented
Hi all, checking in with some updates regarding the Audio Engine,

## Generic Sink implementation in AudioThread
Thanks to the suggestion of @KNOXDEV, it works perfectly. The user can now specify if they want a standard "sink" or a "spatial sink" depending on the values set by by the emitter position, left ear position, and right ear position in `SourceOptions`. Having a nonzero value in any of the three will enforce usage of a SpatialSink. A zero value in all 3 parameters (by default in SourceOptions) signals the usage of a standard Sink

## Manipulating singular audio threads
Since this is possibly not going to be a big issue until later, I'm putting this off for now. When we need the functionality we can choose to add more to the AudioSource impl

## Reading from path buffer rather than loading a source from memory
Also Fixed, I did some of my own research on the topic, and found that you can clone a Buffered `Source` from Rodio. Thus, I changed my implementation to utilize these Buffered sources in order to improve playback speeds.

Under suggestion of the team, I have also downloaded and uploaded all the sample audio files we have so far (unedited, with credits), and modified the readme with a basic example of usage.

2022-05-17 02:24 UTC, potor10 commented
Added proper error handling instead of `unwrap()`

2022-05-17 03:38 UTC, KNOXDEV requested changes
Hey Peter, excellent, amazing work on the high level feedback. I couldn't have asked for better.

I've given some low-level feedback, but it's up to your discretion to see which points you want to work on. I've been purposefully nitpicky here (since I personally tend to find that more useful), so feel free to disregard anything you feel like isn't a good use of your time.

Again, most of these are minor Rust-related conventions. Let me know if you have any questions!

Thanks again Peter!

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    self.clean();
running clean everywhere to prune unused audio sinks feels a little bit of a code smell to me, but after reading the rodio documentation I have yet to come up with a better solution. Either way, it'll work for now.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    let source = match source {
In the places where you do `match()` to handle `Some` and `None`, you might be able to use `if let` to save yourself some typing. https://doc.rust-lang.org/rust-by-example/flow_control/if_let.html

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    self.clean();
I think the only other way to handle this is to put some kind of artificial limit on the number of audio threads and just reuse them. That said I think I prefer the way you've handled it.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +    thread::spawn(move || {
This is a wee bit hacky. The good news is that I found how to do this in rodio! It's buried very far, I found it by using the search bar in the documentation.

I think you can do `source.take_duration().set_filter_fadeout()` https://docs.rs/rodio/latest/rodio/source/struct.TakeDuration.html#method.set_filter_fadeout

Let me know if this saves you some trouble in this method.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +      let active_thread = self.threads.pop();
Just be aware that according to [Rodio](https://docs.rs/rodio/latest/rodio/struct.Sink.html), as soon as you "drop" a Sink (ie, the Sink's go out of scope), audio playback will stop. That doesn't appear to affect this particular implementation because you do some thread stuff to make the sink fadeout work, but it might come up if you change it as I've commented.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    while i < self.threads.len() {
for all of the following methods that loop over the threads and call a function, I recommend you just do `self.threads.iter_mut().for_each` and pass a closure instead. http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/iterators.html

I won't duplicate this comment on `resume`, `stop`, `set_volume`, etc, but the same principle applies.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/context/mod.rs
> +    let (_stream, stream_handle) = match output_stream {
in this case `expect` is equivalent.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +enum AudioSinkType {
Perfect!

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +      AudioSinkType::Spatial(sink) => sink.pause(),
having to do this `match` every time feels a little silly but I'm not exactly sure how we would simplify...

I think at the end of the day we have to blame the authors of Rodio for not using a trait for these structs when it was clearly the correct move.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +      AudioSinkType::Spatial(sink) => sink.pause(),
Especially since the solution would pretty much just be wrapping these structs in another common trait.

2022-05-17 03:38 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +      AudioSinkType::Spatial(sink) => sink.pause(),
no tasking here btw just commenting

2022-05-17 14:54 UTC, potor10 commented on chariot-client/src/audio/thread/mod.rs
> +    thread::spawn(move || {
Yup! I actually found this as well while doing research on the lib.
The issue with this function, I believe, is that it fades out from the end of the audio source. 

This means that regardless of what is playing, we won't experience a fade out until the audio has reached the end. In the case of music, this could be minutes away!

That's why I made the fade out automate on another thread, so we can immediate request a fade out for a certain duration when we want.

2022-05-17 15:20 UTC, potor10 commented
# New Updates

> not necessarily a have-to-fix for this PR, but once you hit like three levels of type nesting, you might wanna create a type alias to refer to it. https://doc.rust-lang.org/reference/items/type-aliases.html

Type alias has been added! Thanks for the tip

> I'm not sure what the difference is between unwrap_or_else -> panic and expect but I think expect is more brief.

I think they are pretty similar, but I've changed them over to `expect()` be consistent.

> for all of the following methods that loop over the threads and call a function, I recommend you just do self.threads.iter_mut().for_each and pass a closure instead. http://web.mit.edu/rust-lang_v1.25/arch/amd64_ubuntu1404/share/doc/rust/html/book/first-edition/iterators.html

Yup, I was able to implement the for_each with a closure on all of those methods

Also, I've actually changed the implementation from `Vec` to `HashMap` for both Track & Thread management.

With HashMap we can use the File names as keys for requesting the buffered audio sources. We can also track & maintain threads in a much more ordered fashion. This actually solves the issue of manipulating singular audio threads. We can do all of that now.

> I think this while loop over an increment variable can be simplified to a for loop over self.threads.iter_mut().
Does that throw an error because of concurrent modification? That makes sense.
In which case, look at using the [retain method defined on Vectors](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.retain).

`retain()` has been implemented on clean, and `drain()` has been implemented on `fade_all_threads`

2022-05-17 19:23 UTC, KNOXDEV requested changes
Minor points, Peter. Looking very good!

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    self.threads.drain().for_each(|(_id, thread)| {
Perfect solution! Wasn't even thinking of it.

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    self.thread_ct = self.thread_ct + 1;
this feels a little...questionable to me. Why not just use `self.threads.len()`?

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +  source: Buffered<Decoder<BufReader<File>>>,
I notice you don't use the type alias you created here, but you can easily share it!

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +  pub fn getId(&mut self) -> u64 {
gonna reiterate what Alistair said, getters and setters are discouraged in Rust.
https://www.reddit.com/r/rust/comments/d7w6n7/is_it_idiomatic_to_write_setters_and_getters/

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +  pub fn getId(&mut self) -> u64 {
Instead, consider just making `thread_id` public.

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +      //self.sink.append(rpt_src);
just remove these comments when you get the chance. Comments are good, commented-out code doesn't need to be there.

2022-05-17 19:23 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +    thread::spawn(move || {
> Yup! I actually found this as well while doing research on the lib. The issue with this function, I believe, is that it fades out from the end of the audio source.
> 
> This means that regardless of what is playing, we won't experience a fade out until the audio has reached the end. In the case of music, this could be minutes away!

I see, but doesn't `take_duration()` accept a duration to end after? The impression I got from that is that you should be able to say "end in two seconds" when do you that.

2022-05-20 00:59 UTC, TheCrossBoy commented
Update:
- @potor10 will be working tonight to get more changes in!
- Hopefully we can get it integrated into the client soon as well
- I am able to provide feedback once it's in a satisfactory state!

2022-05-20 14:45 UTC, potor10 commented on chariot-client/src/audio/thread/mod.rs
> +    thread::spawn(move || {
Hmm, according to rodio docs, `take_duration()` returns a `TakeDuration<>` Source, which means in order for us to use `take_duration()` we cannot give up ownership of the source (which appending to a sink will do). 
https://docs.rs/rodio/latest/rodio/struct.Sink.html#method.append

This means our best attempt at doing a fade_out using this method would be to store another copy of a source, track how long the thread has been alive, and use `skip_duration()` followed by `take_duration()` and the fade_out. 

So we do `stop()` to empty the sink, before doing `append(source.skip_duration().take_duration().set_filter_fadeout())` Generally, this usually results in a super choppy mess, and it doesn't really work at all.

I don't believe there are no inbuilt functions in sink to track the current playtime of a sample, so the best we can do is track the lifetime of the thread, which generally tends to be super inaccurate and results in serious cuts and chops.

2022-05-20 14:51 UTC, potor10 commented on chariot-client/src/audio/mod.rs
> +    self.thread_ct = self.thread_ct + 1;
I updated it in the most recent commit to be more clear about what it does
`self.thread_ct` has the purpose of tracking the maximum thread id that we currently have out. 
We need to store this value, because there is a chance that using a random `u64` in a hashtable will give us a collision with a currently existing thread. 

This value increases whenever there is no available thread ids for free use, and assigns itself to the newest generated threads.

Previous Implementation: A random unordered Vec<AudioSource> which prevented us from grabbing a specific audio thread from the currently playing group. We could assign IDs to each thread (which I eventually did anyways) but to get a specific thread would be O(n) runtime

Current Implementation: A hashtable storing u64 id key with AudioSource value pairs . A user can request a specific key to obtain the requested pair in O(1) time.

2022-05-20 15:39 UTC, KNOXDEV commented on chariot-client/src/audio/thread/mod.rs
> +    thread::spawn(move || {
Hey Peter, the documentation on this is super weak but [by diving into the source I was able to find what Sink does to modify the source after playing has started](https://docs.rs/rodio/latest/src/rodio/sink.rs.html#74).

TLDR, it uses the PeriodicAccess filter with a closure that captures some of the environment to set the source to the configuration settings of the Sink every 5 millisecons. I think this should be the approach you emulate since you know it will work.

2022-05-20 15:42 UTC, KNOXDEV commented on chariot-client/src/audio/mod.rs
> +    self.thread_ct = self.thread_ct + 1;
Oh that's cool.
I think Josh / Nick had to solve this same problem in the resource manager. See if this would also solve your problem, since it seems a little less error prone: https://github.com/ucsd-cse125-sp22/cse125-sp22-group1/blob/main/chariot-client/src/resources/mod.rs#L83

2022-05-20 15:48 UTC, KNOXDEV commented
One last comment, can you look into adding all these sounds to the [Chaired Drive](https://drive.google.com/drive/u/0/folders/15lMRdrPnF4swE1D9H9jeMP6LyWI5xRbT)? I think we should check the audio into there for consistency rather than committing them to main. 

Additionally, is it possible to use ogg as the audio format? Its pretty popular for games as I understand it.

2022-05-20 20:44 UTC, potor10 commented
I'll see if I can run the audio files through an online converter or ffmpeg

2022-05-23 04:39 UTC, TheCrossBoy approved these changes
as the great alistair says, shock em

2022-05-23 04:39 UTC, merged