Add minimal framework for particle simulation
ucsd-cse125-sp22/cse125-sp22-group1 pull request #4
Opened 2022-04-04 07:58 UTC by alistairgray42

Stage 1 of a physics engine is a particle simulation. Particles have position, velocity, and mass, but not dimensions. Steps to complete this (and thus the PR) are

- Calculating the value of all forces we care about (see functions from `sum_of_forces_on_object` for the list) 
- Moving the object each time step based on the sum of the forces and other data from the previous step

Draft PR at the moment - not a lot of content so far, so mostly looking for feedback on structure (are the functions I'm making the right kind of functions, should we be using fancy things like traits anywhere)

2022-04-05 08:10 UTC, alistairgray42 commented on chariot-server/src/physics/constants.rs
> +pub const GRAVITY_COEFFICIENT: f64 = 1.0;
So all the constants in here are meant to be changed once we actually start playing, but they should at least be in the right kind of ballpark for now so that physics generally works as expected (e.g. friction moving an object back isn't stronger than forward motion, so things go in the right direction) - i think these values are fine but yeah that's something in particular to convince yourself about

2022-04-06 07:14 UTC, alistairgray42 commented
Requested review from Aaron for Rust conventions, anyone else feel free to review as well

2022-04-06 08:29 UTC, alistairgray42 commented on chariot-server/src/physics/constants.rs
> +pub const GRAVITY_COEFFICIENT: f64 = 1.0;
same comment applies but these have moved - see `chariot-core/settings`

2022-04-06 16:50 UTC, trulyronak commented
Note - you're committing changes to Cargo.lock, likely from prior stages of the repo when we allowed Cargo.lock files - you'll need to remove those changes from the repo so it doesn't change anything in the repo

2022-04-06 18:11 UTC, alistairgray42 commented
> Quick comment: does it make sense to have the physics simulation structs in chariot-core if only the server is going to simulating physics?
> 
> I would put everything in chariot-server until we know we have a concrete need for something to also be in chariot-core.

The client needs some of this information (e.g. position, angle facing) to be able to render properly - it doesn't need things like velocity or momentum, but splitting that off into a server-only struct while still sending this stuff back and forth seemed inelegant to me. All of this is very much state, and in the minimal MVP all state gets sent back and forth a lot.

2022-04-06 18:11 UTC, alistairgray42 commented
> Quick comment: does it make sense to have the physics simulation structs in chariot-core if only the server is going to simulating physics?
> 
> I would put everything in chariot-server until we know we have a concrete need for something to also be in chariot-core.

The client needs some of this information (e.g. position, angle facing) to be able to render properly - it doesn't need things like velocity or momentum, but splitting that off into a server-only struct while still sending this stuff back and forth seemed inelegant to me. All of this is very much state, and in the minimal MVP all state gets sent back and forth a lot.

2022-04-06 18:17 UTC, KNOXDEV commented
> The client needs some of this information (e.g. position, angle facing) to be able to render properly - it doesn't need things like velocity or momentum, but splitting that off into a server-only struct while still sending this stuff back and forth seemed inelegant to me. All of this is very much state, and in the minimal MVP all state gets sent back and forth a lot.

I would argue physics and networking can and should be separate concerns. If you don't like the idea of translating physics structures (which include information about velocity) into networking structures (which concern position and orientation) then perhaps we should take the position and orientation information, put them into their own structure (say, `Entity`) in chariot-core, but then have `PhysicsProperties` *contain* an Entity alongside all of the other physics stuff. When it comes time to transmit the important networking stuff, we only send the nested Entity struct.

How does that sound?

2022-04-06 18:25 UTC, KNOXDEV requested changes
Here's my feedback. Can you take a look? 

Thanks a bunch Alistair, this looks really solid. The tests are a nice touch.

2022-04-06 18:25 UTC, KNOXDEV commented on chariot-core/src/physics_object.rs
> +	pub linear_momentum: DVec3, // redundant with velocity; both are used for convenience's sake
Redundancy can introduce inconsistency. Have one value and add a method to quickly calculate the other.

2022-04-06 18:25 UTC, KNOXDEV commented on chariot-core/src/settings.rs
> +	pub gravity_coefficient: f64,
can you add some comments describing what these are each used for?

2022-04-06 18:25 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +pub fn do_physics_step(previous_props: &PhysicsProperties, time_step: f64) -> PhysicsProperties{
maybe convert this to an `impl fn` on PhysicsProperties?

2022-04-06 18:25 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +pub fn do_physics_step(previous_props: &PhysicsProperties, time_step: f64) -> PhysicsProperties{
same for the other functions in this file

2022-04-06 18:25 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +pub fn sum_of_forces_on_object(object: &PhysicsProperties) -> DVec3
also, if you have specific sources for these formulas, including the links via comments would be delightful

2022-04-06 20:42 UTC, alistairgray42 commented
> I would argue physics and networking can and should be separate concerns. If you don't like the idea of translating physics structures (which include information about velocity) into networking structures (which concern position and orientation) then perhaps we should take the position and orientation information, put them into their own structure (say, Entity) in chariot-core, but then have PhysicsProperties contain an Entity alongside all of the other physics stuff. When it comes time to transmit the important networking stuff, we only send the nested Entity struct.

I'm game to separate these concerns, but I think there are three categories of data here rather than two:
* Information sent from client to server - this is whether the player is accelerating / braking / turning (currently: `engine_status`, `rotation_status`)
* Information sent from server to client - position and orientation of vehicles (currently: `position`, `velocity`, `unit_steer_direction`; in the future, perhaps more to support the third dimension)
* Server-internal physics simulation information (currently: `mass`, `angular_velocity`; of course the simulation also uses data in the other categories)

I propose having, respectively, `PlayerControls`, `EntityLocation`, and `PhysicsProperties` structs: the client sends `PlayerControls`  to the server and receives `EntityLocation`s, while `PhysicsProperties` on the server contains both of those. `PlayerControls` and `EntityLocation` would live in core, while `PhysicsProperties` would only be on the server. (not married to those names by the way, naming things is hard)

Thoughts?

2022-04-07 02:21 UTC, KNOXDEV commented
> I propose having, respectively, `PlayerControls`, `EntityLocation`, and `PhysicsProperties` structs: the client sends `PlayerControls` to the server and receives `EntityLocation`s, while `PhysicsProperties` on the server contains both of those. `PlayerControls` and `EntityLocation` would live in core, while `PhysicsProperties` would only be on the server. (not married to those names by the way, naming things is hard)
> 
> Thoughts?

Good idea, lets do it.

* I think EntityLocation is good
* I would probably do PlayerInputs instead of PlayerControls
* I would maybe do PlayerEntity instead of PhysicsProperties

2022-04-07 16:25 UTC, KNOXDEV requested changes
Can you rename chariot-core/src/physics_object.rs since the name isn't really applicable anymore? I'm thinking player_inputs.rs, and then sticking EntityLocation into another file as well if possible.

2022-04-07 16:32 UTC, KNOXDEV commented on chariot-server/src/physics/mod.rs
> +fn test_accelerating() {
Tests should go in a tests module. They can either be in this file or in a tests.rs file in the same folder. 
https://doc.rust-lang.org/rust-by-example/testing/unit_testing.html

2022-04-07 16:33 UTC, KNOXDEV commented
@alistairgray42 passing back to you, when you're ready for the final check, just click this button to pass the review back to me:
![image](https://user-images.githubusercontent.com/5607614/162252876-dcffc42d-129c-4aa7-b492-dc3a86e147e8.png)

2022-04-08 22:18 UTC, KNOXDEV reviewed
@alistairgray42 finished looking at this, I love it. I noticed in physics/mod.rs, you have some tests in a test module but some are not. Was this intentional?

As soon as we get that cleared up, that'll be an approval for me. Great work.

2022-04-09 03:11 UTC, KNOXDEV approved these changes
i release you my sweet child

2022-04-09 03:11 UTC, merged