Create dynamic minimap
ucsd-cse125-sp22/cse125-sp22-group1 pull request #52
Opened 2022-05-15 22:56 UTC by alistairgray42

not ready yet!

dependency on #51 to be able to actually display this

2022-05-17 21:27 UTC, alistairgray42 commented on chariot-client/src/graphics.rs
> +        let texture = self.renderer.create_texture2D_init(
I just kinda copied this stuff from the text example; Nick, is it as bad of an idea as it sounds to create a new texture and UI layer each renderer tick?

2022-05-18 18:24 UTC, nickwn commented on chariot-client/src/graphics.rs
> +        let texture = self.renderer.create_texture2D_init(
If it's real time then sure but I would try not to. Sorry for mentioning this now, but I think it actually might be easier to have the track and all players as their own UILayerTechnique, then update their vertex buffers each frame to move them around and let the gpu composite everything when rendering. The vertex buffer can be updated using something like `renderer.write_buffer(ui_layer.vertex_buffer, data)`. The UILayerTechniques for the individual players could just use a 1x1 texture for now.

2022-05-20 00:41 UTC, TheCrossBoy commented
Updates:
- Currently waiting on the changes mentioned by nic and other visual tweaks
- Lower priority than terrain collisions
- Will be picked back up after the above!

2022-05-21 10:17 UTC, alistairgray42 commented on chariot-client/src/graphics.rs
> +            let new_vertex_buffer = UILayerTechnique::create_vertex_buffer(
@nickwn this feels somewhat less silly (but silly kinda silly tbh); thoughts?

2022-05-21 10:19 UTC, alistairgray42 commented
![image](https://user-images.githubusercontent.com/28539155/169647199-df92420b-d14d-4e68-8b08-b994d7d4dc8f.png)

2022-05-21 13:58 UTC, TheCrossBoy requested changes
Good stuff! I will note it is slightly off, but I think it's close enough that for now it should be okay: ![2022-05-21_06-42-29](https://user-images.githubusercontent.com/15060061/169654968-35129d49-c533-461d-b12c-17e25962d4ec.png)

Just see if you can get the `write_buffer` to work and this will be all thumbs up from me!

2022-05-21 13:58 UTC, TheCrossBoy commented on chariot-client/src/graphics.rs
> +    minimap_ui: UIDrawable,
We're starting to have a lot of UIDrawable things start to interact with one another. Perhaps we should have some kind of `Vec<UIDrawable>` to keep track of this, that way we don't have to edit the struct every time we want to add something?

This may be added in the UI PR, but it seemed pertinent to mention it here at least!

2022-05-21 13:58 UTC, TheCrossBoy commented on chariot-client/src/graphics.rs
> +            )
We should be able to (hypothetically) get more exact values from this, but it's probably close enough for now

2022-05-21 13:58 UTC, TheCrossBoy commented on chariot-client/src/graphics.rs
> +            player_layer.vertex_buffer = new_vertex_buffer;
(I can't add a add this comment to my review without having it not respond to yours, so pretend I'm responding to your comment)
You shouldn't have to create a whole new buffer, you should be able to do something like `renderer.write_buffer(player_layer.vertex_buffer, verts_data [from UILayerTechnique::create_vertex_buffer])`, and it should update the buffer without having to create a whole new one

2022-05-22 02:07 UTC, nickwn approved these changes
Looks good, but it would be nice to have a talk with everyone on how the UI should be organized, since I don't think its healthy to keep adding to graphics.rs

2022-05-22 04:01 UTC, alistairgray42 commented on chariot-client/src/graphics.rs
> +            )
i made it somewhat close enough-er but it's very annoying to mess with these values so i'm done with that for now

2022-05-22 04:12 UTC, trulyronak approved these changes
bussing

2022-05-22 04:52 UTC, TheCrossBoy approved these changes
Very cool :)

2022-05-22 04:53 UTC, merged