Having a real game to play!
ucsd-cse125-sp22/cse125-sp22-group1 pull request #56
Opened 2022-05-17 21:59 UTC by TheCrossBoy

Going to be working on the major hurdles preventing us from having a real game going. Mostly server side, client will be informed but visuals for it will likely not be on this PR.

- [ ] Separate states for choosing playing parameters vs loading into the game
- [ ] Let the client actually pick a chair
- [ ] See if connections to the server can be handled asynchronously, so we can choose chairs and maps before everyone has loaded
- [ ] Restructure connecting logic so less stuff is required beforehand
- [ ] Don't load the map on the client until the server tells you to
- [ ] Load specific chairs for players, rather than the default one
- [ ] Spawn players into the map ready to race
- [ ] After everyone has completed the race, be in a "post game" view before returning to the parameter selection screen

Will be trying to work on this as much as possible over the next few days, because it's sort of the basis of... well everything.

2022-05-18 03:43 UTC, trulyronak commented on chariot-server/src/game/phase.rs
> + * 1. GamePhase::ChoosingSettingsAndConnecting
shouldn't there be an earlier stage, waiting for players to connect? because until the players connect, we can't even get to this stage

2022-05-19 18:06 UTC, TheCrossBoy commented
Alright as of now everything seems to be working from (Start server/client) -> (post-game), the transition from (post-game) -> (pre-game) is the only thing not working.
Looks like there will need to be more work done to ensure the previous stuff is "un-rendered", and the server is properly able to accept new stuff from the client. 

also should make sure the server unloads the map as well, just thought of that too

2022-05-19 22:37 UTC, trulyronak requested changes
pretty much good to go, added some comments (that i will resolve myself) to improve maintainabiliy + readability

2022-05-19 22:37 UTC, trulyronak commented on chariot-client/src/application.rs
> +            self.game.pick_chair("standard".to_string());
should make all the chairs an enum type

2022-05-19 22:37 UTC, trulyronak commented on chariot-client/src/game.rs
> +    pub fn pick_chair(&mut self, chair: String) {
would be best to make chair a shared enum

2022-05-19 22:37 UTC, trulyronak commented on chariot-client/src/game.rs
> +    pub fn pick_map(&mut self, map: String) {
similar, maps should be an enum

2022-05-19 22:37 UTC, trulyronak commented on chariot-client/src/graphics.rs
> +        // todo!();
nit: shouldn't keep any commented code

2022-05-19 22:37 UTC, trulyronak commented on chariot-core/src/settings.rs
> +            .set_default("default_map_vote", "track")?
don't think this needs to be customized in settings, it's already changable by the players + by the default implementation

2022-05-19 23:14 UTC, trulyronak approved these changes
a little biased, but this lgtm!

2022-05-19 23:18 UTC, merged